version: '3'

services:
  web:
    labels:
      traefik.http.services.web.loadbalancer.server.port: 8080
      traefik.http.routers.web.rule: 'Host(`${WEB_DOMAIN}`)'
      traefik.http.routers.web.tls: 'true'
      traefik.http.routers.web.tls.certresolver: 'default'
  # see https://github.com/EugenMayer/docker-image-traefik
  traefik:
    image: eugenmayer/traefik:2.x
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_CHALLENGE: 'http'
      TRAEFIK_HTTPS_ENABLE: 'only'
      TRAEFIK_DOCKER_ENABLE: 'true'
      TRAEFIK_DOCKER_EXPOSEDBYDEFAULT: 'false'
    volumes:
      - certs:/mnt/certs
      - filestorage:/mnt/filestorage
      - acme:/mnt/acme
      # mount our docker socket so our docker container can be discovered
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  certs:
  filestorage:
  acme:
