version: '3'

services:
  config:
    image: ghcr.io/eugenmayer/concourse-configurator:7.x
    volumes:
      - concourse-keys-web:/concourse-keys/web
      - concourse-keys-worker:/concourse-keys/worker
    restart: unless-stopped
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
    image: concourse/concourse:${CONCOURSE_VERSION}
    command: web
    depends_on:
      - config
      - db
    ports:
      - 2222:2222
    volumes:
      - concourse-keys-web:/concourse-keys
    restart: on-failure # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_LOG_LEVEL: ${LOG_LEVEL:-error}
      CONCOURSE_TSA_LOG_LEVEL: ${LOG_LEVEL:-error}
      CONCOURSE_BAGGAGECLAIM_LOG_LEVEL: ${LOG_LEVEL:-error}
      CONCOURSE_GARDEN_LOG_LEVEL: ${LOG_LEVEL:-error}
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: ${DB_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${DB_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${DB_NAME}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_ENABLE_LIDAR: 'false'
      # see https://concourse-ci.org/concourse-web.html#resource-defaults
      CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS: ${CONCOURSE_BASE_RESOURCE_TYPE_DEFAULTS:-defaults.yml}
volumes:
  pgdata:
    driver: local
  concourse-keys-web:
    driver: local
  concourse-keys-worker:
    driver: local
#  concourse-worker1-state:
#    driver: local
