version: "2"

services:
  config:
    environment:
      VAULT_ENABLED: 1
      VAULT_DO_AUTOCONFIGURE: 1
    volumes:
      - vault-server-config:/vault/server
      - vault-client-config:/vault/concourse
  vault:
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    image: vault:0.9.0
    cap_add:
      - IPC_LOCK
    depends_on:
      - config
    ports:
      - 8200:8200
    volumes:
      - vault-server-config:/vault/config
    command: vault server -config /vault/config/vault.hcl
  web:
    # ensure we know where the self signed cert is
    command: web --vault-ca-cert /vault/client/server.crt
    depends_on:
      - vault
      - config
    environment:
      CONCOURSE_VAULT_URL: https://vault:8200
      CONCOURSE_VAULT_TLS_INSECURE_SKIP_VERIFY: "true"
      CONCOURSE_VAULT_AUTH_BACKEND: cert
      CONCOURSE_VAULT_PATH_PREFIX: /secret/concourse
      CONCOURSE_VAULT_CLIENT_CERT: /vault/client/cert.pem
      CONCOURSE_VAULT_CLIENT_KEY: /vault/client/key.pem
    volumes:
      # needed to share the self signed cert and the auth cert
      - vault-client-config:/vault/client
volumes:
  vault-server-config:
    driver: local
  vault-client-config:
    driver: local