version: '3'

services:
  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  worker:
    image: concourse/concourse:${CONCOURSE_VERSION:-7.5}
    command: worker
    privileged: true
    stop_signal: SIGUSR2
    depends_on:
      - config
      - web
    volumes:
      - concourse-keys-worker:/concourse-keys
      - concourse-worker1-state:/worker-state
    environment:
      CONCOURSE_TSA_HOST: 'web:2222'
      CONCOURSE_BAGGAGECLAIM_DRIVER: ${CONCOURSE_BAGGAGECLAIM_DRIVER:-overlay}
      CONCOURSE_RUNTIME: ${CONTAINER_RUNTIME:-containerd}

volumes:
  concourse-worker1-state:
    driver: local
