version: "2"

services:
  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  worker:
    image: concourse/concourse:5.0.0
    command: worker
    privileged: true
    depends_on:
      - config
      - web
    volumes:
      - concourse-keys-worker:/concourse-keys
    #  - concourse-worker1-state:/worker-state
    environment:
      # port is mandatory with 4.x .. port syntax required
      CONCOURSE_TSA_HOST: "web:2222"
      CONCOURSE_BAGGAGECLAIM_DRIVER: ${CONCOURSE_BAGGAGECLAIM_DRIVER}

