version: "2"

services:
  config:
    image: eugenmayer/concourse-configurator:5.x
    volumes:
      - concourse-keys-web:/concourse-keys/web
      - concourse-keys-worker:/concourse-keys/worker
    restart: unless-stopped

  db:
    image: postgres:10.7
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
    image: concourse/concourse:5.2.0
    command: web
    depends_on:
      - config
      - db
    volumes:
      - concourse-keys-web:/concourse-keys
    restart: on-failure # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: ${DB_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${DB_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${DB_NAME}
      CONCOURSE_EXTERNAL_URL: ${EXTERNAL_URL}
volumes:
  pgdata:
    driver: local
  concourse-keys-web:
    driver: local
  concourse-keys-worker:
    driver: local
#  concourse-worker1-state:
#    driver: local


