version: "2"

services:
  config:
    image: eugenmayer/concourse-configurator
    volumes:
      - concourse-keys-web:/concourse-keys/web
      - concourse-keys-worker:/concourse-keys/worker
    restart: unless-stopped

  vault:
    image: vault:0.9
    cap_add:
      - IPC_LOCK
    # we do not  want to open this port for now, since we can use the configurator to talk to vault
    # ports: ["8200:8200"]
    volumes:
      - ./keys/vault:/vault/config
    command: vault server -config /vault/config/vault.hcl

  db:
    image: postgres:10.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  web:
    image: concourse/concourse:3.8.0
    command: web
    depends_on:
      - config
      - db
    volumes:
      - concourse-keys-web:/concourse-keys
    restart: unless-stopped # required so that it retries until conocurse-db comes up
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${ADMIN_USER}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${ADMIN_PASSWORD}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_EXTERNAL_URL}
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: ${DB_USER}
      CONCOURSE_POSTGRES_PASSWORD: ${DB_PASSWORD}
      CONCOURSE_POSTGRES_DATABASE: ${DB_NAME}

  # see https://github.com/concourse/concourse-docker/blob/master/Dockerfile
  worker:
    # not using concourse/concourse:3.6.0 du to https://github.com/EugenMayer/docker-image-concourseci-worker-solid
    image: eugenmayer/concourse-worker-solid:3.8.0
    #image: concourse/concourse:3.6.0
    privileged: true
    #hostname: worker1
    depends_on:
      - config
      - web
    volumes:
      - concourse-keys-worker:/concourse-keys
    #  - concourse-worker1-state:/worker-state
    environment:
      CONCOURSE_TSA_HOST: web
      CONCOURSE_BAGGAGECLAIM_DRIVER: ${CONCOURSE_BAGGAGECLAIM_DRIVER}

volumes:
  pgdata:
    driver: local
  concourse-keys-web:
    driver: local
  concourse-keys-worker:
    driver: local
#  concourse-worker1-state:
#    driver: local


