jobs:
  - name: vault-test
    serial: true
    build_logs_to_retain: 100
    plan:
    - get: boilerplate
    - task: echo-vault-value
      file: boilerplate/examples/vault-based/tasks/task1.yml
      params:
        VAULT_VALUE1: ((firstvalue))
        VAULT_VALUE2: ((lower_level_secondvalue))
        # this value wont work, since concourseci does not support nested values - do not use them
        VAULT_WONTWORK1: ((nested/value))
        VAULT_OBJ_USER: ((obj.user))
        VAULT_OBJ_PASSWORD: ((obj.password))
        # you can also not use something like foo.bar as ket for consul

resources:
  - name: boilerplate
    type: git
    source:
      uri: https://github.com/EugenMayer/concourseci-server-boilerplate
