jobs:
  - name: simple-pipeline
    serial: true
    build_log_retention:
      builds: 5
    plan:
      - get: eugemayer-traefik-git
      - get: eugemayer-traefik
        params:
          skip_download: true

resources:
  - name: eugemayer-traefik
    type: docker-image
    source:
      repository: eugenmayer/traefik
      tag: 2.x

  - name: eugemayer-traefik-git
    type: git
    source:
      uri: https://github.com/EugenMayer/docker-image-traefik.git
      branch: master
