platform: linux

params:
  VAULT_VALUE1:
  VAULT_VALUE2:
  VAULT_OBJ_USER:
  VAULT_OBJ_PASSWORD:

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: 3.6

inputs:

outputs:

run:
  path: /bin/sh
  user: root
  args:
  - '-lc'
  - |
    # just echo the vault values we bound to the task params from the pipeline
    echo ${VAULT_VALUE1}
    echo ${VAULT_VALUE2}
    echo ${VAULT_OBJ_USER}
    echo ${VAULT_OBJ_PASSWORD}
